Instance: PromotionAndTreatmentQuestionnaire
InstanceOf: Questionnaire
Title: "Promotion and Treatment  Questionnaire"
Description: "Data elements for the counselling and treatment task of the workflow							"
Usage: #definition
* status = #draft
* experimental = false

* contained[+] = IptpDose112VS
* contained[+] = ANCLABMalePartnerSelfTestingKitResultsVS
* contained[+] = ANCLABAnaemiaDiagnosisVS
* contained[+] = ANCLABMalariaDiagnosisVS
* contained[+] = FollowUpFrequencyVS
* contained[+] = ANC.B10.PreventiveDewormingAntihelminthicTreatmentProvidedVS
* contained[+] = PregnantWomanReceivedAsReferralFromVS

* item[+].linkId = "diagnosesGroup"
* item[=].text = "Diagnoses"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB8GestationalAgeAtTodaysVisitCat"
  * item[=].text = "Gestational age at today's visit (Auto-calculated)"
  * item[=].type = #integer
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10HypertensionDiagnosis"
  * item[=].text = "Hypertension"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#ANCLABAnaemiaDiagnosisVS"

  * item[+].linkId = "ancAncB10PreEclampsiaDiagnosis"
  * item[=].text = "Pre-eclampsia "
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB9AnaemiaDiagnosis"
  * item[=].text = "Anaemia"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#ANCLABAnaemiaDiagnosisVS"

  * item[+].linkId = "ancAncB9HepatitisBDiagnosis"
  * item[=].text = "Hepatitis B"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatDiabetesInPregnancyDiagnosis"
  * item[=].text = "Diabetes in Pregnancy"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatElevatedFastingBloodSugarDiagnosis"
  * item[=].text = "Elevated fasting blood sugar"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB9SyphilisDiagnosis"
  * item[=].text = "Syphilis"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncMalariaDiagnosis"
  * item[=].text = "Malaria"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#ANCLABMalariaDiagnosisVS"

  * item[+].linkId = "ancAncKidneyDiseaseChronicRenalFailureDiagnosis"
  * item[=].text = "Kidney disease (Chronic Renal Failure)"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncCardiacConditionDiagnosis"
  * item[=].text = "Cardiac condition"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncChronicAsthmaDiagnosis"
  * item[=].text = "Chronic asthma"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamThrombocytopeniaDiagnosis"
  * item[=].text = "Thrombocytopenia"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "recommendedTreatmentBasedOnDiagnosisAutoGeneratedGroup"
* item[=].text = "Recommended treatment based on diagnosis (Auto-generated)"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancPatHypertensiveTreatmentProvided"
  * item[=].text = "Hypertensive Treatment Provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancCatMagnesiumSulphateProvided"
  * item[=].text = "Loading dose of Magnesium Sulphate provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamSickleCellScreeningFolicAcid5mgDaily"
  * item[=].text = "Folic acid 5mg/daily"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamSickleCellScreeningAdmitToHospitalIfComplicationsDevelop"
  * item[=].text = "Admit to hospital for Sickle cell screening if complications develop"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncCatAdmitAndMonitor"
  * item[=].text = "Admit and Monitor"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncAdmitAndDeliver"
  * item[=].text = "Admit for delivery due to Hypertension"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancCatFollowUpProvided"
  * item[=].text = "Type of follow up suggested to patient"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#FollowUpFrequencyVS"

  * item[+].linkId = "ancCatFollowUpFrequencySpecify"
  * item[=].text = "Specify follow up frequency"
  * item[=].type = #string
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatHepatitisBTreatmentProvided"
  * item[=].text = "Hepatitis B treatment provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatSimpleMalariaTreatmentProvided"
  * item[=].text = "Simple malaria treatment provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatSyphilisTreatmentProvided"
  * item[=].text = "Syphilis Treatment Provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "otherMedicationsAndPrescriptionsGivenGroup"
* item[=].text = "Other medications and prescriptions given"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB7ProphylacticIronAndFolicAcidIfaProvidedAtLeast30Tablets"
  * item[=].text = "Prophylactic Iron and folic acid (IFA) provided. At least 30 tablets"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB7FolicAcidFaProvidedAtleast30Tablets"
  * item[=].text = "Folic acid (FA) provided. Atleast 30 tablets"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10IptpSpDoseProvided"
  * item[=].text = "IPTp-SP dose provided"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#IptpDose112VS"

  * item[+].linkId = "ancAncB10DateIptpSpDoseWasProvided"
  * item[=].text = "Date IPTp-SP dose was provided"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10aIptpCtxDoseProvided"
  * item[=].text = "IPTp-CTX dose provided"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#IptpDose112VS"

  * item[+].linkId = "ancAncB10aDateIptpCtxDoseWasProvided"
  * item[=].text = "Date IPTp-CTX dose was provided"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10PreventiveDewormingAntihelminthicTreatmentProvided"
  * item[=].text = "Preventive deworming  antihelminthic treatment provided"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#ANC.B10.PreventiveDewormingAntihelminthicTreatmentProvidedVS"

  * item[+].linkId = "ancAncB10LlinsProvided"
  * item[=].text = "LLINs provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncLabMalePartnerSelfTestingKitProvided"
  * item[=].text = "Male partner self testing kit provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncLabMalePartnerSelfTestingKitResults"
  * item[=].text = "Male Partner self testing kit results"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#ANCLABMalePartnerSelfTestingKitResultsVS"

  * item[+].linkId = "ancPatArvProphylaxisForTheUnBornInfantsProvided"
  * item[=].text = "ARV prophylaxis for the un born infants provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAn27cMalePartnerSyphilisTreatmentProvided"
  * item[=].text = "Male Partner syphilis treatment provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "counsellingBasedOnDiagnosisGroup"
* item[=].text = "Counselling based on diagnosis"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB10CounsellingConductedOnAnaemia"
  * item[=].text = "Counselling conducted on anaemia"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnHypertension"
  * item[=].text = "Counselling conducted on hypertension"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnGestationalDiabetesMellitusGdm"
  * item[=].text = "Counselling conducted on gestational diabetes mellitus (GDM)"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnDiabetesMellitusDm"
  * item[=].text = "Counselling conducted on diabetes mellitus (DM)"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnSyphilis"
  * item[=].text = "Counselling conducted on syphilis"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnTbScreeningPositive"
  * item[=].text = "Counselling conducted on TB screening positive"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnHivPositive"
  * item[=].text = "Counselling conducted on HIV positive"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnHepatitisBPositive"
  * item[=].text = "Counselling conducted on hepatitis B positive"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatCounselOnTheIncreasedRiskOfDevelopingPreEclampsiaDueToCrf"
  * item[=].text = "Counsel on the increased risk of developing pre-eclampsia due to CRF"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamCounsellingOnSickleCellScreeningBasedOnFindingsMonitorHbAtEveryVisit"
  * item[=].text = "Counselling on Sickle cell screening based on findings; monitor Hb at every visit"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "behaviouralCounsellingGroup"
* item[=].text = "Behavioural counselling "
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB10CounsellingOnTobaccoCessation"
  * item[=].text = "Counselling on smoking cessation"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnCondomUse"
  * item[=].text = "Counselling on condom use"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnAlcoholUse"
  * item[=].text = "Counselling on alcohol use"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnMalariaPrevention"
  * item[=].text = "Counselling on malaria prevention"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnHealthyEatingAndKeepingPhysicallyActive"
  * item[=].text = "Counselling on healthy eating and keeping physically active"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnBalancedEnergyAndProteinDietarySupplementation"
  * item[=].text = "Counselling on balanced energy and protein dietary supplementation"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "counsellingBasedOnPastPregnancyComplicationsGroup"
* item[=].text = "Counselling based on past pregnancy complications"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB10CounsellingOnRiskOfPreEclampsia"
  * item[=].text = "Counselling on risk of pre-eclampsia"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatCounsellingOnRiskOfEclampsia"
  * item[=].text = "Counselling on risk of eclampsia"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnRiskOfGestationalDiabetesMellitusGdm"
  * item[=].text = "Counselling on risk of gestational diabetes mellitus (GDM)"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamCounsellingOnHospitalDeliveryDueToPreviousAssistedDelivery"
  * item[=].text = "Counselling on hospital delivery due to previous assisted delivery"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatCounsellingOnHospitalDeliveryDueToPreviousPerinealTear3rdOr4thDegree"
  * item[=].text = "Counselling on hospital delivery due to previous perineal tear (3rd or 4th degree) "
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB9HighRiskForHiv"
  * item[=].text = "High risk for HIV"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnHivRisk"
  * item[=].text = "Counselling conducted on HIV risk"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatCounsellingOnHospitalDeliveryDueToPreviousNeonatalDeath"
  * item[=].text = "Counselling on hospital delivery due to previous neonatal death"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "immunizationsTetanusDiptheriaHepatitisBGroup"
* item[=].text = "Immunizations: Tetanus-Diptheria, Hepatitis B"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB10TetanusDiptheriaTd1ImmunizationProvided"
  * item[=].text = "Tetanus-Diptheria (TD) 1 immunization provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10TetanusDiptheriaTd1ImmunizationDate"
  * item[=].text = "Tetanus-Diptheria (TD) 1 immunization Date"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10TetanusDiptheriaTd2ImmunizationProvided"
  * item[=].text = "Tetanus-Diptheria (TD) 2 immunization provided"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10TetanusDiptheriaTd2ImmunizationDate"
  * item[=].text = "Tetanus-Diptheria (TD) 2 immunization Date"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10HepatitisB1ImmunizationDate"
  * item[=].text = "Hepatitis B-1 immunization Date"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10HepatitisB2ImmunizationDate"
  * item[=].text = "Hepatitis B-2 immunization Date"
  * item[=].type = #date
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "generalAncCounsellingDangerSignsScheduleBirthPlanGroup"
* item[=].text = "General ANC counselling: Danger signs, Schedule, Birth Plan"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB10CounsellingConductedOnSeekingCareWhenDangerSignsOccur"
  * item[=].text = "Counselling conducted on seeking care when danger signs occur"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnAncContactScheduleConducted"
  * item[=].text = "Counselling on ANC contact schedule conducted"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnBirthPreparednessAndComplicationsReadiness"
  * item[=].text = "Counselling conducted on birth preparedness and complications readiness"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnRhFactorNegative"
  * item[=].text = "Counselling conducted on Rh factor negative"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnPostpartumFamilyPlanningConducted"
  * item[=].text = "Counselling on postpartum family planning conducted"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingConductedOnBreastfeeding"
  * item[=].text = "Counselling conducted on breastfeeding"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingOnMaternalNutrition"
  * item[=].text = "Counselling on maternal nutrition"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB10CounsellingInfantFeeding"
  * item[=].text = "Counselling on infant feeding"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

* item[+].linkId = "referralsAndAdmissionsGroup"
* item[=].text = "Referrals and admissions"
* item[=].type = #group
* item[=]
  * item[+].linkId = "ancAncB11ReceivedAsReferral"
  * item[=].text = "Received as Referral"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancAncB11IfYesReceivedAsReferralFrom"
  * item[=].text = "If yes, received as Referral from;"
  * item[=].type = #choice
  * item[=].repeats = false
  * item[=].required = false
  * item[=].answerValueSet = "#PregnantWomanReceivedAsReferralFromVS"

  * item[+].linkId = "ancAncB11ReferredToHigherLevelClinicOnIndication"
  * item[=].text = "Referred to higher level clinic on indication"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancReferToHcivOrHospitalForSevereAnaemiaTreatmentDueToHaemoglobin"
  * item[=].text = " Refer to HCIV or Hospital for Severe Anaemia treatment due to haemoglobin"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancReferToHcivOrHospitalForHepatitisBTreatment"
  * item[=].text = "Refer to HCIV or Hospital for Hepatitis B treatment"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatReferToCemoncFacilityForLabour"
  * item[=].text = "Refer to CEMONC facility for labour"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatReferToHcivOrHospitalForFollowUpAndMedicationDueToHyperglycemia"
  * item[=].text = "Refer to HCIV or Hospital for follow-up and medication due to Hyperglycemia"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatReferToHcIvHospitalForFollowUpOfElevatedFastingBloodSugar"
  * item[=].text = "Refer to HC IV/Hospital for follow-up of elevated fasting blood sugar"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancReferToHcIvHospitalForFollowUpOfElevatedRandomBloodSugar"
  * item[=].text = "Refer to HC IV/Hospital for follow-up of elevated random blood sugar"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPamSickleCellScreeningReferToASickleCellClinicIfNotYetRegistered"
  * item[=].text = "Refer to a sickle-cell clinic, if not yet registered"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancReferToHcivOrHospitalForComplicatedMalariaTreatment"
  * item[=].text = " Refer to HCIV or Hospital for complicated malaria treatment"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatReferToHcivOrHospitalDueToNoFetalHeartBeatPresent"
  * item[=].text = "Refer to HCIV or Hospital due to no Fetal Heart beat present"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false

  * item[+].linkId = "ancPatReferForTreatmentAndSupportAccordingToFindingsOfGbv"
  * item[=].text = "Refer for treatment and support according to findings of GBV"
  * item[=].type = #boolean
  * item[=].repeats = false
  * item[=].required = false


