CodeSystem: Dhis2DataElementsCS
Id: dhis2-data-elements-cs
Title: "DHIS2 Data Elements"
Description: "Code system for 315 unique DHIS2 data elements from all selected programs"
* #w1XaGkyql1u "ANC - ANC.B6. Alcohol" "ANC - ANC.B6. Alcohol"
* #xSKiFlohuQd "ANC - ANC.B6. History of Early Neonatal Death (between 0 and 7 days of birth)" "ANC - ANC.B6. History of Early Neonatal Death (between 0 and 7 days of birth)"
* #cCp43HMY3br "ANC - ANC.B6. Diabetes" "ANC - ANC.B6. Diabetes"
* #oeojmvdEY9S "ANC - ANC.B6. Eclampsia/Convulsions" "ANC - ANC.B6. Eclampsia/Convulsions"
* #Ru01omP2WCQ "ANC - ANC.B6. Expected date of delivery (EDD)" "ANC - ANC.B6. Expected date of delivery (EDD)"
* #w9p8MQDRyMr "ANC - ANC.B6. Gestational age" "ANC - ANC.B6. Gestational age"
* #XhGh2s0tPTr "ANC - ANC History of big baby delivery ( &gt; 4 kg)" "ANC - ANC History of big baby delivery ( > 4 kg)"
* #lYE2KzWQGkW "ANC - ANC.B6. HIV status profile" "ANC - ANC.B6. HIV status profile"
* #iboAokLxCIh "ANC - ANC Myomectomy" "ANC - ANC Myomectomy"
* #QqTuhQQgpcp "ANC - ANC.B6. Hypertension" "ANC - ANC.B6. Hypertension"
* #fuEUJqslhPb "ANC - ANC Cardiac condition" "ANC - ANC Cardiac condition"
* #KPN571DvV4D "ANC - ANC.B6. Kidney disease (Chronic Renal Failure)" "ANC - ANC.B6. Kidney disease (Chronic Renal Failure)"
* #w4ky6EkVahL "ANC - ANC.B6. Last normal menstrual period (LNMP) date" "ANC - ANC.B6. Last normal menstrual period (LNMP) date"
* #joirdYETe8d "ANC - ANC.B6. Clinical estimation (Palpation/fundal height) date" "ANC - ANC.B6. Clinical estimation (Palpation/fundal height) date"
* #l7Jh3IoeEIa "ANC - ANC.B6. Malaria medication (sulfadoxine-pyrimethamine)" "ANC - ANC.B6. Malaria medication (sulfadoxine-pyrimethamine)"
* #I7dvwZGNgE8 "ANC - ANC.B6. Para" "ANC - ANC.B6. Para"
* #PuiTfPfSf86 "ANC - ANC.B6. Number of pregnancies (gravida)" "ANC - ANC.B6. Number of pregnancies (gravida)"
* #Juv31inY35a "ANC - ANC.B6 Ultrasound GA" "ANC - ANC.B6 Ultrasound GA"
* #DPZ6kIgtiIA "ANC - ANC.B6. No alcohol and/or substances" "ANC - ANC.B6. No alcohol and/or substances"
* #snqxJUEWgkb "ANC - ANC.B6. No chronic or past health conditions" "ANC - ANC.B6. No chronic or past health conditions"
* #V16g2TRV7MB "ANC - ANC.B6. No known allergies" "ANC - ANC.B6. No known allergies"
* #DSAooZSxopi "ANC - ANC.B6. No known past surgeries" "ANC - ANC.B6. No known past surgeries"
* #hpXvhGzaVld "ANC - ANC.B6. No medications" "ANC - ANC.B6. No medications"
* #GWxtXap1Guk "ANC - ANC.B6. No past pregnancy complications" "ANC - ANC.B6. No past pregnancy complications"
* #j3lxVBnaXmy "ANC - ANC.B6. Number of caesarean sections" "ANC - ANC.B6. Number of caesarean sections"
* #p4e5Y0GQIxv "ANC - ANC.B6. Number of abortions" "ANC - ANC.B6. Number of abortions"
* #fpPtP8xrU1s "ANC - ANC.B6. Number of stillbirths (FSD and/or MSD)" "ANC - ANC.B6. Number of stillbirths (FSD and/or MSD)"
* #vpxAELVdkqn "ANC - ANC.B6. Other allergies (specify)" "ANC - ANC.B6. Other allergies (specify)"
* #hz94MekJLYe "ANC - ANC.B6. Other gynecological procedures (specify)" "ANC - ANC.B6. Other gynecological procedures (specify)"
* #kyOjlg4co4z "ANC - ANC.B6. Medications (specify)" "ANC - ANC.B6. Medications (specify)"
* #rF7OJIP7fhp "ANC - ANC.B6. Other past pregnancy problems (specify)" "ANC - ANC.B6. Other past pregnancy problems (specify)"
* #lbmrnYizavt "ANC - ANC.B6. Other (specify)" "ANC - ANC.B6. Other (specify)"
* #UZ6Re4zVePj "ANC - ANC.B6. Other substance use (specify)" "ANC - ANC.B6. Other substance use (specify)"
* #S6O8strHi1p "ANC - ANC.B6. Other surgeries (specify)" "ANC - ANC.B6. Other surgeries (specify)"
* #TGcfgzv8mQA "ANC - ANC.B6. Pre-eclampsia" "ANC - ANC.B6. Pre-eclampsia"
* #RPSgZF1i0hk "ANC - ANC.B6. Source of gestational age" "ANC - ANC.B6. Source of gestational age"
* #HvfStK1Mfo5 "ANC - ANC.B6. Tobacco use" "ANC - ANC.B6. Tobacco use"
* #PrDdlt8U65H "ANC - ANC.B6. Ultrasound date" "ANC - ANC.B6. Ultrasound date"
* #YKXci7Sm0Zq "ANC.B6. Clinically estimated gestational age" "ANC.B6. Clinically estimated gestational age"
* #TcOkQ8Qqmlt "ANC - ANC.B8. Height" "ANC - ANC.B8. Height"
* #kFwQfziJLEt "ANC - ANC.B8. Pre-gestational weight" "ANC - ANC.B8. Pre-gestational weight"
* #UZnz5QLRvcr "ANC - ANC.B8. BMI" "ANC - ANC.B8. BMI"
* #UsYtsHtuvwQ "ANC - ANC.B8. Weight category" "ANC - ANC.B8. Weight category"
* #bzupYCgg4m6 "ANC - ANC.B8a. Review and confirm computed BMI" "ANC - ANC.B8a. Review and confirm computed BMI"
* #ztZwHRN9iPM "ANC - ANC.B8. Expected weight gain" "ANC - ANC.B8. Expected weight gain"
* #L6Toy2TrHHq "ANC - ANC.B8. Body temperature" "ANC - ANC.B8. Body temperature"
* #dyYdfamSY2Z "ANC - ANC.B8. Diastolic blood pressure" "ANC - ANC.B8. Diastolic blood pressure"
* #c6Cg8KgNu77 "ANC - ANC.B8. Fetal heartbeat present" "ANC - ANC.B8. Fetal heartbeat present"
* #cY03odVgQqq "ANC - ANC.B8. Fetal heart rate" "ANC - ANC.B8. Fetal heart rate"
* #vPdXnmGWzfy "ANC - ANC.B8. Fetal presentation" "ANC - ANC.B8. Fetal presentation"
* #rC2RDuM8wb2 "ANC - ANC.B8. Oedema Leg swelling" "ANC - ANC.B8. Oedema Leg swelling"
* #YrtUVQtPngs "ANC - ANC.B8. Symptoms of severe pre-eclampsia present" "ANC - ANC.B8. Symptoms of severe pre-eclampsia present"
* #PN6HcGjTraL "ANC - ANC.B8. Number of fetuses" "ANC - ANC.B8. Number of fetuses"
* #jETdi1M2DY9 "ANC - ANC.B8. Oedema of the hands and feet" "ANC - ANC.B8. Oedema of the hands and feet"
* #ULV28awvMXH "ANC - ANC.B8. Oedema present" "ANC - ANC.B8. Oedema present"
* #SrpLUqMjW97 "ANC - ANC.B8. Oedema severity" "ANC - ANC.B8. Oedema severity"
* #EyfTU3ibMmJ "ANC - ANC.B8. Pallor present" "ANC - ANC.B8. Pallor present"
* #Q3s82wdeOZg "ANC - ANC.B8. Pelvic exam result (visual)" "ANC - ANC.B8. Pelvic exam result (visual)"
* #kNrTQqC1bgg "ANC - ANC.B8. Pitting ankle oedema" "ANC - ANC.B8. Pitting ankle oedema"
* #yQyFSrY3S0q "ANC - ANC.B8. Pitting lower back oedema" "ANC - ANC.B8. Pitting lower back oedema"
* #C47wV4EBLaS "ANC - ANC.B8. Pulse rate" "ANC - ANC.B8. Pulse rate"
* #MqZDsOZm4yD "ANC - ANC.B8. Repeat diastolic blood pressure" "ANC - ANC.B8. Repeat diastolic blood pressure"
* #ZkCYYlI4xe7 "ANC - ANC.B8. Repeat systolic blood pressure" "ANC - ANC.B8. Repeat systolic blood pressure"
* #fjZ4KQpS1QS "ANC - ANC.B8. Symphysis-fundal height (SFH)" "ANC - ANC.B8. Symphysis-fundal height (SFH)"
* #M4HEOoEFTAT "ANC - ANC.B8. Systolic blood pressure" "ANC - ANC.B8. Systolic blood pressure"
* #VEFV1QayfzE "ANC - ANC.B8. Signs/conditions for GBV" "ANC - ANC.B8. Signs/conditions for GBV"
* #d8vfOWb6SPd "ANC - ANC.B8. Other abnormal pelvic exam (visual) result (specify)" "ANC - ANC.B8. Other abnormal pelvic exam (visual) result (specify)"
* #vMVLu4hlDqx "ANC - Previous scar 1" "ANC - Previous scar 1"
* #tsaVZFUAgkD "ANC - ANC.B8. Other fetal presentation (specify)" "ANC - ANC.B8. Other fetal presentation (specify)"
* #fDdSgAwUbtS "ANC - Previous scar year 1" "ANC - Previous scar year 1"
* #UAwQzN7SMAi "ANC - Previous Scar Indication 1" "ANC - Previous Scar Indication 1"
* #nN3JSNtFAo8 "ANC - Previous scar 2" "ANC - Previous scar 2"
* #b3qArrNwpz0 "ANC - Previous scar year 2" "ANC - Previous scar year 2"
* #wha8HRwqFtD "ANC - Previous Scar Indication 2" "ANC - Previous Scar Indication 2"
* #hITbUr6ufTz "ANC - ANC.B7. Experiencing Cough lasting more than 2 weeks" "ANC - ANC.B7. Experiencing Cough lasting more than 2 weeks"
* #a7gTKszpdVp "ANC - Previous scar 3" "ANC - Previous scar 3"
* #WBBaer7NTFJ "ANC - ANC.B7. Hospitalisation for what" "ANC - ANC.B7. Hospitalisation for what"
* #LSIsLB6epXX "ANC - Previous scar year 3" "ANC - Previous scar year 3"
* #ydqILDGfoRp "ANC - ANC.B8. MUAC" "ANC - ANC.B8. MUAC"
* #ytarRo3GlhD "ANC - Previous Scar Indication 3" "ANC - Previous Scar Indication 3"
* #EFKE1hMUpkM "ANC - Previous scar 4" "ANC - Previous scar 4"
* #jhv8rdTd1sf "ANC - ANC.B8. MUAC Color code" "ANC - ANC.B8. MUAC Color code"
* #PIIZ3ngYzxf "ANC - Previous scar year 4" "ANC - Previous scar year 4"
* #N2MadZlBXiJ "ANC - ANC.B8. Nutritional status" "ANC - ANC.B8. Nutritional status"
* #gnZ35nEqJmI "ANC - ANC.B8. Relation presenting part" "ANC - ANC.B8. Relation presenting part"
* #xZ2QZYotcKT "ANC - Previous Scar Indication 4" "ANC - Previous Scar Indication 4"
* #zZzZazs1DGi "ANC - ANC.B7. Experiencing Contractions" "ANC - ANC.B7. Experiencing Contractions"
* #eF3VGluAlcm "ANC - ANC.B7. Experiencing Fever" "ANC - ANC.B7. Experiencing Fever"
* #QhijDzMdFNq "ANC - ANC.B7. Experiencing Severe Headache" "ANC - ANC.B7. Experiencing Severe Headache"
* #VLcb1WBMTIH "ANC - ANC.B8. Second fetal heart rate" "ANC - ANC.B8. Second fetal heart rate"
* #SM7dVOLQD8j "ANC - ANC.B7. Experiencing Vaginal bleeding" "ANC - ANC.B7. Experiencing Vaginal bleeding"
* #xa10dHKgRWa "ANC - ANC.B7. Experiencing Excessive Vomiting" "ANC - ANC.B7. Experiencing Excessive Vomiting"
* #cPOXL8JV8Ee "ANC - ANC.B7. Has abnormal vaginal discharge (physiological) (foul smelling) (curd like)" "ANC - ANC.B7. Has abnormal vaginal discharge (physiological) (foul smelling) (curd like)"
* #syAvZ78FCls "ANC - ANC.B8. Gestational age at today&#x27;s visit_ANC" "ANC - ANC.B8. Gestational age at today's visit_ANC"
* #H90qsZViPcS "ANC - ANC.B8. Current  weight" "ANC - ANC.B8. Current  weight"
* #qmgotDEO8YI "ANC - ANC.B5. Pain –Extreme pelvic pain/cannot walk (symphysis pubis dysfunction)" "ANC - ANC.B5. Pain –Extreme pelvic pain/cannot walk (symphysis pubis dysfunction)"
* #J3ijwQYXVSV "ANC - ANC.B8. Total weight gain (kg)" "ANC - ANC.B8. Total weight gain (kg)"
* #WWGGsY8l88G "ANC - ANC.B5. Pain –Other" "ANC - ANC.B5. Pain –Other"
* #bXVD2EMF7UW "ANC - ANC Visit Number" "ANC - ANC Visit Number"
* #Kyw7NtFeW3B "ANC - ANC.B7. No physiological symptoms" "ANC - ANC.B7. No physiological symptoms"
* #KZT7yfzeP08 "ANC - ANC.B7. Other current physiological symptoms (specify)" "ANC - ANC.B7. Other current physiological symptoms (specify)"
* #xb4Z245Bnej "ANC - ANC.B5. Regular ANC / Scheduled visit?" "ANC - ANC.B5. Regular ANC / Scheduled visit?"
* #CORtBqRWjMG "ANC - ANC.B7. Fetal movement" "ANC - ANC.B7. Fetal movement"
* #LI3bLtFxT8h "ANC - ANC.B5. Specify health concern" "ANC - ANC.B5. Specify health concern"
* #wi3jkKJNjr7 "ANC - ANC.B9. Random blood sugar result" "ANC - ANC.B9. Random blood sugar result"
* #S3bsJ9ogxeN "ANC - ANC.B9.  Blood haemoglobin test date" "ANC - ANC.B9.  Blood haemoglobin test date"
* #eddQQbyYaEv "ANC - ANC.B9.  Blood group" "ANC - ANC.B9.  Blood group"
* #Dp1hN6EwLnh "ANC - ANC.B9.  Blood screening test date" "ANC - ANC.B9.  Blood screening test date"
* #rEAO5q6BnSJ "ANC - ANC.B9.  Hepatitis B test date" "ANC - ANC.B9.  Hepatitis B test date"
* #vDkIpVMAYPU "ANC - ANC.B9.  Hepatitis B test result" "ANC - ANC.B9.  Hepatitis B test result"
* #YREFGI3SapQ "ANC - ANC.B9. eMTCT test date" "ANC - ANC.B9. eMTCT test date"
* #zo8VyJRKcmi "ANC - ANC.B9.  eMTCT HIV test result" "ANC - ANC.B9.  eMTCT HIV test result"
* #liA7cL3lyMp "ANC - ANC.B9.  TB screening incomplete (symptoms only)" "ANC - ANC.B9.  TB screening incomplete (symptoms only)"
* #xXuuXz5xfh6 "ANC - ANC.B9.  Other test(s) date" "ANC - ANC.B9.  Other test(s) date"
* #HjA9hp3NCFA "ANC - ANC.B9.  Other test(s) name" "ANC - ANC.B9.  Other test(s) name"
* #UsM907MWnA5 "ANC - ANC.B9.   Other test(s) result(s)" "ANC - ANC.B9.   Other test(s) result(s)"
* #ox8s78VJC1R "ANC -ANC.B9.  Partner HIV test date" "ANC -ANC.B9.  Partner HIV test date"
* #ODqCU8tNjq5 "ANC - LAB CD4 results" "ANC - LAB CD4 results"
* #ZtpsckiEhGB "ANC - LAB Viral load results" "ANC - LAB Viral load results"
* #MhC6OCNIFOZ "ANC - ANC.B9.  Partner HIV test result" "ANC - ANC.B9.  Partner HIV test result"
* #OAVexurF9i0 "ANC - LAB WHO Clinical stage" "ANC - LAB WHO Clinical stage"
* #cBuumo9jGRc "ANC - ANC Platelets" "ANC - ANC Platelets"
* #fixliM4mt3T "ANC - ANC LAB Pregnant woman linked to ART" "ANC - ANC LAB Pregnant woman linked to ART"
* #SuC9foMX1Ea "ANC - ANC LAB Pregnant woman ART number" "ANC - ANC LAB Pregnant woman ART number"
* #Yycea04JKAR "ANC - ANC Lab Pregnant woman ART location" "ANC - ANC Lab Pregnant woman ART location"
* #I4OPKBwhGQ0 "ANC - ANC LAB Date Viral load sample collected" "ANC - ANC LAB Date Viral load sample collected"
* #noAWcXSpCaP "ANC - ANC LAB Date Viral load sample returned" "ANC - ANC LAB Date Viral load sample returned"
* #GLFICGeB5Ap "ANC - ANC LAB Viral load status" "ANC - ANC LAB Viral load status"
* #D40sUAJilcj "ANC - ANC LAB Date CD4 sample collected" "ANC - ANC LAB Date CD4 sample collected"
* #SnHImni1u5k "ANC - LAB Symptoms of complicated malaria" "ANC - LAB Symptoms of complicated malaria"
* #xem63QqjPNK "ANC - ANC LAB Date CD4 sample returned" "ANC - ANC LAB Date CD4 sample returned"
* #p6wWb8I2jyo "ANC - ANC.B9.  Rh factor" "ANC - ANC.B9.  Rh factor"
* #XST9vCca14R "ANC - ANC.B9.  Syphilis test date" "ANC - ANC.B9.  Syphilis test date"
* #gueCJt1Cjru "ANC - ANC.B9.  Syphilis test result" "ANC - ANC.B9.  Syphilis test result"
* #jORfSq3dc0Z "ANC - ANC.B9.  TB test date" "ANC - ANC.B9.  TB test date"
* #vB0KLtHeSft "ANC - ANC.B9.  TB test result" "ANC - ANC.B9.  TB test result"
* #P0WhE9bsD1E "ANC - ANC.B9.  Ultrasound scan date" "ANC - ANC.B9.  Ultrasound scan date"
* #ZP8aN3M1U51 "ANC - ANC.B9.  Urine dipstick result –glucose" "ANC - ANC.B9.  Urine dipstick result –glucose"
* #n7ITb3GsUNi "ANC - ANC.B9.  Urine dipstick result –leukocytes" "ANC - ANC.B9.  Urine dipstick result –leukocytes"
* #z1iDiVtSw43 "ANC - ANC.B9.  Urine dipstick result –nitrites" "ANC - ANC.B9.  Urine dipstick result –nitrites"
* #PpxBOihc1Y6 "ANC - ANC.B9.  Urine dipstick result –protein" "ANC - ANC.B9.  Urine dipstick result –protein"
* #EnLWXRgiimk "ANC - ANC.B9.  Blood glucose test date" "ANC - ANC.B9.  Blood glucose test date"
* #pV0OABcFZCu "ANC - ANC LAB Sickle cell" "ANC - ANC LAB Sickle cell"
* #pMYNlTxqieX "ANC - ANC LAB Partner ART Number" "ANC - ANC LAB Partner ART Number"
* #jHwhKRgeemY "ANC - ANC LAB Partner age" "ANC - ANC LAB Partner age"
* #mXYhBhAPXJL "ANC - ANC LAB Partner linked to ART " "ANC - ANC LAB Partner linked to ART "
* #ccy0efIWFb8 "ANC - ANC Lab Partner ART location" "ANC - ANC Lab Partner ART location"
* #dN6k6agVKUu "ANC - ANC.B9.  Partner Syphilis test result" "ANC - ANC.B9.  Partner Syphilis test result"
* #bUQy6eZfqFR "ANC - ANC B9.DE Urine dipstick test date" "ANC - ANC B9.DE Urine dipstick test date"
* #pnR1TFOb4xU "ANC - ANC LAB Malaria B/S for MPs" "ANC - ANC LAB Malaria B/S for MPs"
* #VrSrCgpxTT3 "ANC - ANC LAB Pus cells" "ANC - ANC LAB Pus cells"
* #NUzZqwCQcms "ANC - ANC.B9. Fasting blood sugar result" "ANC - ANC.B9. Fasting blood sugar result"
* #qNSSCV58TD2 "ANC - ANC.B9.  Blood haemoglobin result" "ANC - ANC.B9.  Blood haemoglobin result"
* #CqOqQVk2Vqw "ANC - ANC LAB Urine Microscopy date" "ANC - ANC LAB Urine Microscopy date"
* #HJZAwP1vt7T "ANC - ANC LAB Malaria RDT" "ANC - ANC LAB Malaria RDT"
* #g2BFjUIJ5G9 "ANC - ANC LAB Malaria test date" "ANC - ANC LAB Malaria test date"
* #CzjBxEJ6HrQ "ANC - ANC.B8. Gestational age at todays visit_LAB" "ANC - ANC.B8. Gestational age at todays visit_LAB"
* #e7cIfEBpsZb "ANC - ANC.B9.  HIV test recommended" "ANC - ANC.B9.  HIV test recommended"
* #RKjAsZ2EKa7 "ANC - ANC.B9.  Hepatitis B test recommended" "ANC - ANC.B9.  Hepatitis B test recommended"
* #KYxA0A2j8DB "ANC - ANC.B9.  Syphilis test recommended" "ANC - ANC.B9.  Syphilis test recommended"
* #aKJK1ZXz2GP "ANC - ANC.B9.  Ultrasound recommended" "ANC - ANC.B9.  Ultrasound recommended"
* #rqMrshNZgg8 "ANC - ANC.B9. Urine test recommended" "ANC - ANC.B9. Urine test recommended"
* #oOQvM7ZPnTj "ANC - ANC.B9.  TB screening recommended" "ANC - ANC.B9.  TB screening recommended"
* #Y0MfiRhxr1a "ANC - ANC.B9.  Haemoglobin test recommended" "ANC - ANC.B9.  Haemoglobin test recommended"
* #Uxcgpc4oTCf "ANC - ANC.B9.  Blood screening recommended" "ANC - ANC.B9.  Blood screening recommended"
* #XJeRbkSaC1J "ANC - ANC.B9. Malaria test recommended" "ANC - ANC.B9. Malaria test recommended"
* #lkrEe3MT5KK "ANC - LAB Ultrasound comments" "ANC - LAB Ultrasound comments"
* #qlR1FedtJRq "ANC - ANC.B10. Counselling conducted on birth preparedness and complications readiness" "ANC - ANC.B10. Counselling conducted on birth preparedness and complications readiness"
* #T2bfkalL2LC "ANC - ANC.B10. Counselling conducted on breastfeeding" "ANC - ANC.B10. Counselling conducted on breastfeeding"
* #jRo4KlnCKeX "ANC - ANC.B10. Counselling conducted on HIV risk" "ANC - ANC.B10. Counselling conducted on HIV risk"
* #l066A1HPqRU "ANC - ANC.B10. Counselling conducted on Rh factor negative" "ANC - ANC.B10. Counselling conducted on Rh factor negative"
* #B2vmUDbtn9u "ANC - ANC.B10. Counselling conducted on seeking care when danger signs occur" "ANC - ANC.B10. Counselling conducted on seeking care when danger signs occur"
* #QZ00NKZNNHf "ANC - ANC.B10. Counselling on ANC contact schedule conducted" "ANC - ANC.B10. Counselling on ANC contact schedule conducted"
* #vI7Bj0uD9rO "ANC - ANC.B10. Counselling on postpartum family planning conducted" "ANC - ANC.B10. Counselling on postpartum family planning conducted"
* #hGRDCZ9eyEK "ANC - ANC.B10. Hepatitis B-1 immunization Date" "ANC - ANC.B10. Hepatitis B-1 immunization Date"
* #fQcLrBqBS40 "ANC - ANC.B10. Tetanus-Diptheria (TD) 1 immunization Date" "ANC - ANC.B10. Tetanus-Diptheria (TD) 1 immunization Date"
* #mkH2mlYqWqB "ANC - ANC.B10. Date IPTp-SP dose was provided" "ANC - ANC.B10. Date IPTp-SP dose was provided"
* #maAtPdJhov5 "ANC - ANC.B10. Counselling on risk of gestational diabetes mellitus (GDM)" "ANC - ANC.B10. Counselling on risk of gestational diabetes mellitus (GDM)"
* #cwUiNQdsXCd "ANC - PAT. Simple Malaria Treatment Provided" "ANC - PAT. Simple Malaria Treatment Provided"
* #tSzje3cW2hQ "ANC - ANC.B10. Counselling on risk of pre-eclampsia" "ANC - ANC.B10. Counselling on risk of pre-eclampsia"
* #pBclCe2kriA "ANC - ANC.B7. Folic acid (FA) provided. Atleast 30 tablets" "ANC - ANC.B7. Folic acid (FA) provided. Atleast 30 tablets"
* #BEcBoTxdJxW "ANC -  Refer to HCIV or Hospital for Severe Anaemia treatment due to haemoglobin" "ANC -  Refer to HCIV or Hospital for Severe Anaemia treatment due to haemoglobin"
* #HM1Gwr6X8M3 "ANC -  Refer to HCIV or Hospital for complicated malaria treatment" "ANC -  Refer to HCIV or Hospital for complicated malaria treatment"
* #Euy7gjx9HQQ "ANC - ANC.B10. Tetanus-Diptheria (TD) 1 immunization provided" "ANC - ANC.B10. Tetanus-Diptheria (TD) 1 immunization provided"
* #g9g5XVMRMhg "ANC - Refer to HCIV or Hospital for Hepatitis B treatment" "ANC - Refer to HCIV or Hospital for Hepatitis B treatment"
* #gGcxEhV4uET "ANC - PAT Diabetes in Pregnancy Diagnosis" "ANC - PAT Diabetes in Pregnancy Diagnosis"
* #v2vCvy9JR71 "ANC - PAT Refer to HCIV or Hospital for follow-up and medication due to Hyperglycemia" "ANC - PAT Refer to HCIV or Hospital for follow-up and medication due to Hyperglycemia"
* #ZJ1mIPM587W "ANC - PAT Elevated fasting blood sugar Diagnosis" "ANC - PAT Elevated fasting blood sugar Diagnosis"
* #zKHV3Gf8lf0 "ANC - PAT Refer for treatment and support according to findings of GBV" "ANC - PAT Refer for treatment and support according to findings of GBV"
* #XH5mvacs4fh "ANC - PAT Syphilis Treatment Provided" "ANC - PAT Syphilis Treatment Provided"
* #cLaqvVnoNQW "ANC - ANC.B10. Tetanus-Diptheria (TD) 2 immunization Date" "ANC - ANC.B10. Tetanus-Diptheria (TD) 2 immunization Date"
* #QljEpD4ZXqQ "ANC - ANC.B10. Tetanus-Diptheria (TD) 2 immunization provided" "ANC - ANC.B10. Tetanus-Diptheria (TD) 2 immunization provided"
* #LwXs0S8eD64 "ANC - PAM Counselling on hospital delivery due to previous assisted delivery" "ANC - PAM Counselling on hospital delivery due to previous assisted delivery"
* #vcFw7qq0EyN "ANC - PAT Counselling on risk of eclampsia" "ANC - PAT Counselling on risk of eclampsia"
* #RmYIDSTh06Y "ANC - PAT Counselling on hospital delivery due to previous perineal tear (3rd or 4th degree) " "ANC - PAT Counselling on hospital delivery due to previous perineal tear (3rd or 4th degree) "
* #LWDjK29CquZ "ANC - PAT Counselling on hospital delivery due to previous neonatal death" "ANC - PAT Counselling on hospital delivery due to previous neonatal death"
* #ID6RhUJutpq "ANC - PAT Refer to CEMONC facility for labour" "ANC - PAT Refer to CEMONC facility for labour"
* #CuCWAVnu94F "ANC - ANC Kidney disease (Chronic Renal Failure) Diagnosis" "ANC - ANC Kidney disease (Chronic Renal Failure) Diagnosis"
* #nskowTcgnS3 "ANC - ANC.B10. Counselling conducted on anaemia" "ANC - ANC.B10. Counselling conducted on anaemia"
* #HDQ8F5bQ5GB "ANC - PAT Counsel on the increased risk of developing pre-eclampsia due to CRF" "ANC - PAT Counsel on the increased risk of developing pre-eclampsia due to CRF"
* #ZgVJiTpBIAa "ANC - ANC.B10. Counselling conducted on diabetes mellitus (DM)" "ANC - ANC.B10. Counselling conducted on diabetes mellitus (DM)"
* #GKRmoIpVWBV "ANC - ANC Cardiac condition Diagnosis" "ANC - ANC Cardiac condition Diagnosis"
* #Lzfcin802uv "ANC - ANC Chronic asthma Diagnosis" "ANC - ANC Chronic asthma Diagnosis"
* #hnUK7METcNT "ANC - ANC.B10. Counselling conducted on gestational diabetes mellitus (GDM)" "ANC - ANC.B10. Counselling conducted on gestational diabetes mellitus (GDM)"
* #kpNsJv2MJgQ "ANC - PAM Thrombocytopenia Diagnosis" "ANC - PAM Thrombocytopenia Diagnosis"
* #FlYho8YA6gK "ANC - ANC.B10. Counselling conducted on hepatitis B positive" "ANC - ANC.B10. Counselling conducted on hepatitis B positive"
* #CceCy8lgwJr "ANC - PAT Refer to HC IV/Hospital for follow-up of elevated fasting blood sugar" "ANC - PAT Refer to HC IV/Hospital for follow-up of elevated fasting blood sugar"
* #ONaCQGKKt0u "ANC - PAT Refer to HCIV or Hospital due to no Fetal Heart beat present" "ANC - PAT Refer to HCIV or Hospital due to no Fetal Heart beat present"
* #zO1T2OyE5nV "ANC - ANC.B10. Counselling conducted on HIV positive" "ANC - ANC.B10. Counselling conducted on HIV positive"
* #pdogMM7UXWz "ANC - Refer to HC IV/Hospital for follow-up of elevated random blood sugar" "ANC - Refer to HC IV/Hospital for follow-up of elevated random blood sugar"
* #msP5WbYKajH "ANC - ANC.B10. Counselling conducted on hypertension" "ANC - ANC.B10. Counselling conducted on hypertension"
* #Llteev2Flio "ANC - ANC.B10. Counselling conducted on TB screening positive" "ANC - ANC.B10. Counselling conducted on TB screening positive"
* #sWoYKdJWtLO "ANC - PAM Sickle cell screening Folic acid 5mg/daily" "ANC - PAM Sickle cell screening Folic acid 5mg/daily"
* #qMWTQTWNm0K "ANC - ANC.B10. Counselling on alcohol use" "ANC - ANC.B10. Counselling on alcohol use"
* #M7xOHyaG1XR "ANC - PAM Sickle cell screening Refer to a sickle-cell clinic, if not yet registered" "ANC - PAM Sickle cell screening Refer to a sickle-cell clinic, if not yet registered"
* #YOjc3CiFMku "ANC - PAM Counselling on Sickle cell screening based on findings; monitor Hb at every visit" "ANC - PAM Counselling on Sickle cell screening based on findings; monitor Hb at every visit"
* #YU9wbp4XiOO "ANC - PAM Sickle cell screening Admit to hospital if complications develop" "ANC - PAM Sickle cell screening Admit to hospital if complications develop"
* #YFu1oMAst5N "ANC - ANC.B10. Counselling on condom use" "ANC - ANC.B10. Counselling on condom use"
* #EcAoMGJs9BB "ANC - ANC.B10. Hepatitis B-2 immunization Date" "ANC - ANC.B10. Hepatitis B-2 immunization Date"
* #sw43UG2v6Wk "ANC - ANC.B10a. IPTp-CTX dose provided" "ANC - ANC.B10a. IPTp-CTX dose provided"
* #Jnlp0lDaPSe "ANC - ANC.B10a. Date IPTp-CTX dose was provided" "ANC - ANC.B10a. Date IPTp-CTX dose was provided"
* #G6qtfHN4Vy1 "ANC - ANC.B10. Counselling on healthy eating and keeping physically active" "ANC - ANC.B10. Counselling on healthy eating and keeping physically active"
* #O2SnmbwvwOb "ANC - PAT ARV prophylaxis for the un born infants provided" "ANC - PAT ARV prophylaxis for the un born infants provided"
* #pB9VLth3i2W "ANC - ANC LAB Male partner self testing kit provided" "ANC - ANC LAB Male partner self testing kit provided"
* #GjOg2r7Wvm1 "ANC - ANC LAB Male Partner self testing kit results" "ANC - ANC LAB Male Partner self testing kit results"
* #MXOfQmqSgS8 "ANC - PAT Hepatitis B Treatment Provided" "ANC - PAT Hepatitis B Treatment Provided"
* #VhlH1sYU9fv "ANC - ANC.B10. Counselling on maternal nutrition" "ANC - ANC.B10. Counselling on maternal nutrition"
* #zfF0dZSKfvj "ANC - ANC.B10. Counselling infant feeding" "ANC - ANC.B10. Counselling infant feeding"
* #Ok9OQpitjQr "ANC - ANC.B10. Counselling on tobacco cessation" "ANC - ANC.B10. Counselling on tobacco cessation"
* #VJh6Dw6KcfB "ANC - ANC.B10. Hypertension diagnosis" "ANC - ANC.B10. Hypertension diagnosis"
* #LKNervGK4jq "ANC - ANC.B10. Pre-eclampsia diagnosis" "ANC - ANC.B10. Pre-eclampsia diagnosis"
* #a0ZYAtqVHCx "ANC - ANC.B10. IPTp-SP dose provided" "ANC - ANC.B10. IPTp-SP dose provided"
* #W5AuILld5eW "ANC - ANC.B9.  Anaemia diagnosis" "ANC - ANC.B9.  Anaemia diagnosis"
* #gmbQ72pvjVd "ANC - ANC. Malaria diagnosis" "ANC - ANC. Malaria diagnosis"
* #xYKSnQRs6Fq "ANC - ANC Admit and Deliver" "ANC - ANC Admit and Deliver"
* #rMyGldvXWsQ "ANC - CAT Magnesium Sulphate provided" "ANC - CAT Magnesium Sulphate provided"
* #e2bRsC2xpto "ANC - PAT Hypertensive Treatment Provided" "ANC - PAT Hypertensive Treatment Provided"
* #gwytRk2Uwr6 "ANC - CAT Follow up provided" "ANC - CAT Follow up provided"
* #yoyL0k3CfgO "ANC - CAT Follow up frequency specify" "ANC - CAT Follow up frequency specify"
* #xZvctiDTfmn "ANC -ANC.B10. Preventive deworming antihelminthic treatment provided" "ANC -ANC.B10. Preventive deworming antihelminthic treatment provided"
* #f1KQDCMUyno "ANC - ANC.B7. Prophylactic Iron and folic acid (IFA) provided. At least 30 tablets" "ANC - ANC.B7. Prophylactic Iron and folic acid (IFA) provided. At least 30 tablets"
* #ppiuaHJLXhv "ANC - ANC.B9.  Hepatitis B diagnosis" "ANC - ANC.B9.  Hepatitis B diagnosis"
* #lja34jS4kHc "ANC - ANC.B9.  Syphilis diagnosis" "ANC - ANC.B9.  Syphilis diagnosis"
* #vdPettzpAjK "ANC - ANC.B10. Counselling on balanced energy and protein dietary supplementation" "ANC - ANC.B10. Counselling on balanced energy and protein dietary supplementation"
* #G8eAMYZaXnH "ANC - ANC.B9.  High risk for HIV" "ANC - ANC.B9.  High risk for HIV"
* #jDoejOIyb3a "ANC - ANC CAT Admit and Monitor" "ANC - ANC CAT Admit and Monitor"
* #RrkI8hPNjmb "ANC - ANC.B11. Received as Referral" "ANC - ANC.B11. Received as Referral"
* #LRwXvqpnLAb "ANC - ANC.B11. If yes, received as referral from" "ANC - ANC.B11. If yes, received as referral from"
* #Izr0L8qbpax "ANC - ANC.B10. LLINs provided" "ANC - ANC.B10. LLINs provided"
* #C04Rrelub1N "ANC - ANC.B10. Counselling conducted on syphilis" "ANC - ANC.B10. Counselling conducted on syphilis"
* #HBFvfu6dT1k "ANC - AN27c. Male Partner syphilis treatment provided" "ANC - AN27c. Male Partner syphilis treatment provided"
* #V90TnwOPzNm "ANC - ANC.B10. Counselling on malaria prevention" "ANC - ANC.B10. Counselling on malaria prevention"
* #G1smYf2TE5w "ANC - ANC.B11. Referred to higher level clinic on indication" "ANC - ANC.B11. Referred to higher level clinic on indication"
* #KjLdMpXvJNm "ANC - ANC.B8. Gestational age at todays visit_CAT" "ANC - ANC.B8. Gestational age at todays visit_CAT"
* #VIEg1M2z5Vs "ANC - ANC.End1. Pregnancy outcome" "ANC - ANC.End1. Pregnancy outcome"
* #CfVBzICA1og "ANC - ANC.BD. Term or Preterm" "ANC - ANC.BD. Term or Preterm"
* #DfHmC0s6JqV "ANC - ANC.BD-Date and time of admission" "ANC - ANC.BD-Date and time of admission"
* #zvJl9DSRNl7 "ANC - ANC.BD Single or Multiple Specify number" "ANC - ANC.BD Single or Multiple Specify number"
* #h2xGlXziLV6 "ANC - BD-Gestation of delivery (weeks)" "ANC - BD-Gestation of delivery (weeks)"
* #elQef67mAgb "ANC - ANC.BD-Mode of delivery" "ANC - ANC.BD-Mode of delivery"
* #cCDntJeM21e "ANC - ANC.BD-Sex of child" "ANC - ANC.BD-Sex of child"
* #G38Z5FR4sv7 "ANC - ANC.BD-Date and time of birth (Child)" "ANC - ANC.BD-Date and time of birth (Child)"
* #quFsdF0GLrm "ANC - ANC.BD Weight at birth" "ANC - ANC.BD Weight at birth"
* #Gk5vKpilJJq "ANC - ANC.BD Child vital status" "ANC - ANC.BD Child vital status"
* #dxH6wzY9ll4 "ANC - ANC.BD ARV Rx for Mothers (by type)" "ANC - ANC.BD ARV Rx for Mothers (by type)"
* #dSeYEled4tX "ANC - ANC.BD Obst/prolg labour" "ANC - ANC.BD Obst/prolg labour"
* #z2YaIoUs5eV "ANC - ANC.BD Hysterectomy " "ANC - ANC.BD Hysterectomy "
* #sYgW1IM4Gn5 "ANC - ANC.BD Managed" "ANC - ANC.BD Managed"
* #c975NCuATNP "ANC - ANC.BD PROM/Sepsis" "ANC - ANC.BD PROM/Sepsis"
* #tQ4Sv6kQks9 "ANC - ANC.BD Referred" "ANC - ANC.BD Referred"
* #hGXAH0H7oKs "ANC - ANC.BD Repaired" "ANC - ANC.BD Repaired"
* #ROgwm1UaUjW "ANC - AND.BD-Other Reason for Pregnancy Outcome" "ANC - AND.BD-Other Reason for Pregnancy Outcome"
* #JrSzUmBfKnO "ANC - ANC.BD Eclampsia postpartum hemorrhage " "ANC - ANC.BD Eclampsia postpartum hemorrhage "
* #Mv4z2Sd5s8E "ANC - ANC.BD Ruptured Ux" "ANC - ANC.BD Ruptured Ux"
* #fvnZ3zRQUdQ "ANC - ANC.BD Eclampsia antepartum hemorrhage " "ANC - ANC.BD Eclampsia antepartum hemorrhage "
* #KQ34Vol6R3J "ANC - ANC.BD 0PV Vaccine" "ANC - ANC.BD 0PV Vaccine"
* #U58bt6XckRq "ANC - ANC.BD ARV Px for New Born (By type, HIV)" "ANC - ANC.BD ARV Px for New Born (By type, HIV)"
* #p7e9CE7Hc0t "ANC - ANC.BD Apgar Score" "ANC - ANC.BD Apgar Score"
* #oMjZ429k9Fd "ANC - ANC.BD BCG Vaccine" "ANC - ANC.BD BCG Vaccine"
* #lWDnMWYvjm8 "ANC - ANC.BD Feeding option" "ANC - ANC.BD Feeding option"
* #qw4RPXf7cvO "ANC - ANC.BD HBV birth dose" "ANC - ANC.BD HBV birth dose"
* #GIdnxfQDAFp "ANC - ANC.BD Placenta" "ANC - ANC.BD Placenta"
* #IdElg7sFPAN "ANC - ANC.BD Single or Multiple" "ANC - ANC.BD Single or Multiple"
* #x5AQxjEagnn "ANC - ANC.BD Skin to Skin contact" "ANC - ANC.BD Skin to Skin contact"
* #iAZ4RM1pdpk "ANC - ANC.BD TTC" "ANC - ANC.BD TTC"
* #dC098c6csBv "ANC - ANC.BD Vit K" "ANC - ANC.BD Vit K"
* #i5LaKr2e845 "ANC - ANC.BD length at birth" "ANC - ANC.BD length at birth"
* #Og2D0fsxko1 "ANC - ANC.BD-Delivered by (Name)" "ANC - ANC.BD-Delivered by (Name)"
* #QtETpPKw3Sa "ANC - ANC.BD-Delivered by (Signature)" "ANC - ANC.BD-Delivered by (Signature)"
* #af54ISxXZEB "ANC - ANC.BD Still Birth" "ANC - ANC.BD Still Birth"
* #Vyok96daapr "ANC - OUT_POST - Date of postpartum care " "ANC - OUT_POST - Date of postpartum care "
* #iySWXP9NB26 "ANC - OUT_POST - Blood pressure" "ANC - OUT_POST - Blood pressure"
* #jBAsZaO4oEt "ANC - OUT_POST - Temperature" "ANC - OUT_POST - Temperature"
* #YSVwVatx6JR "ANC - OUT_POST - Pulse Rate" "ANC - OUT_POST - Pulse Rate"
* #u4E2vVGtxc5 "ANC - OUT_POST -  PPH" "ANC - OUT_POST -  PPH"
* #Q2iOrrIs8RO "ANC - OUT_POST - Dribbling/leaking urine " "ANC - OUT_POST - Dribbling/leaking urine "
* #dNdQy42gyNN "ANC - OUT_POST - Anemia" "ANC - OUT_POST - Anemia"
* #ONFttMEHeed "ANC - OUT_POST - Vaginal discharge after 4 weeks of delivery" "ANC - OUT_POST - Vaginal discharge after 4 weeks of delivery"
* #wVsbNnQVjuX "ANC - OUT_POST - Pelvic exam " "ANC - OUT_POST - Pelvic exam "
* #xqC5R16ID4N "ANC - OUT_POST - Breast exam " "ANC - OUT_POST - Breast exam "
* #oOENq0HVqnV "ANC - OUT_POST - Iron &amp; Folic Acid (IFA) supplementation" "ANC - OUT_POST - Iron & Folic Acid (IFA) supplementation"
* #dDD0M9NxRiE "ANC - OUT_POST - Counseling danger signs/symptoms, FP, hygiene, nutrition, EPI, use of insecticide-treated net (ITN), breastfeeding, etc. given" "ANC - OUT_POST - Counseling danger signs/symptoms, FP, hygiene, nutrition, EPI, use of insecticide-treated net (ITN), breastfeeding, etc. given"
* #N9NypL64c5O "ANC - OUT_POST - Baby breathing" "ANC - OUT_POST - Baby breathing"
* #c1M2JMkm3En "ANC - OUT_POST - Baby breastfeeding" "ANC - OUT_POST - Baby breastfeeding"
* #bNwTnOIQpxB "ANC - OUT_POST - Baby wt (gm)" "ANC - OUT_POST - Baby wt (gm)"
* #UE5eXlAess0 "ANC - OUT_POST -  Immunization" "ANC - OUT_POST -  Immunization"
* #TFOKxMR2T5A "ANC - OUT_POST -  HIV tested (Y/N)" "ANC - OUT_POST -  HIV tested (Y/N)"
* #V6LHFJ2Kv9l "ANC - OUT_POST -  HIV test result" "ANC - OUT_POST -  HIV test result"
* #mSjUMNDx0Z2 "ANC - OUT_POST - ARV Rx for mother (By type)" "ANC - OUT_POST - ARV Rx for mother (By type)"
* #TlkMcrKmlIa "ANC - OUT_POST - ARV PX" "ANC - OUT_POST - ARV PX"
* #OpRMziOVS8e "ANC - OUT_POST -  Feeding option: EBF/ERF" "ANC - OUT_POST -  Feeding option: EBF/ERF"
* #ghEssGDk4nx "ANC - OUT_POST - Newborn referred to chronic HIV infant care " "ANC - OUT_POST - Newborn referred to chronic HIV infant care "
* #YeXm1Vvny9O "ANC - OUT_POST - FP counseled and provided (by method)" "ANC - OUT_POST - FP counseled and provided (by method)"
* #KcFAQvkTXrW "ANC - OUT_POST - Actions taken" "ANC - OUT_POST - Actions taken"
* #eCoVjkdihM9 "ANC - OUT_Post - Type of Stay" "ANC - OUT_Post - Type of Stay"
